packages:
  - 'apps/client'
  - 'apps/server'
  - 'packages/configs'
ignoredBuiltDependencies:
  - 'unrs-resolver'
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - 'core-js'
  - 'esbuild'
  - 'sharp'
